baseURL = "https://sagemaker-workshop.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amazon SageMaker Workshop"
theme = "hugo-theme-learn"
uglyurls = true
googleAnalytics = "UA-119576367-1"

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Daniele Stroppa"
description = "Amazon SageMaker Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true

[[menu.shortcuts]]
name = "<i class='fa-brands fa-linkedin'></i> Smartworkz"
identifier = "li"
url = "https://www.linkedin.com/company/smartworkznl/about/"
weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
